background_ratio: 0.3
batch_size: 2
clustering_threshold: 0.7
dino_model: facebook/dino-vitb16
frames_per_video: 50
gentle_lr: 1.0e-06
gradient_accumulation_steps: 8
max_epochs: 3
max_retries: 2
min_cluster_size: 5
original_model_checkpoint: F:/Studia/PhD_projekt/VIT/ViTParticleFilterTracker/YOLO_DETR_Benchmarks/models/DETR/checkpoint_epoch_100.pth
output_directory: F:/Studia/PhD_projekt/VIT/ViTParticleFilterTracker/YOLO_DETR_Benchmarks/scripts/DETR_Background_Training/pipeline_output
python_executable: python
timeout_hours: 24
tooltip_annotations_path: F:/Studia/PhD_projekt/VIT/ViTParticleFilterTracker/Annotators/Datasets/Yolo/yolo_dataset_20250218/coco_annotations_from_yolo_dataset_20250218.json
tooltip_dataset_path: F:/Studia/PhD_projekt/VIT/ViTParticleFilterTracker/Annotators/Datasets/Yolo/yolo_dataset_20250218/images/train
tooltip_ratio: 0.7
validation_split: 0.2
video_directory: E:/Cataract/videos/micro
