#!/usr/bin/env python3
"""
Skrypt do tworzenia plików YAML dla datasetu YOLO na podstawie istniejącej struktury.
"""

import argparse
import json
from pathlib import Path
from typing import Dict, List


class YOLOYamlCreator:
    """Tworzy pliki konfiguracyjne YAML dla YOLO."""
    
    def __init__(
        self,
        output_dir: str,
        images_dir: str,
        coco_json_path: str = None,
        class_names: List[str] = None,
        dataset_name: str = "surgical_tools",
        verbose: bool = True
    ):
        self.output_dir = Path(output_dir)
        self.images_dir = Path(images_dir)
        self.coco_json_path = Path(coco_json_path) if coco_json_path else None
        self.class_names = class_names
        self.dataset_name = dataset_name
        self.verbose = verbose
        
        # Sprawdź czy katalogi istnieją
        if not self.output_dir.exists():
            raise FileNotFoundError(f"Katalog wyjściowy nie istnieje: {self.output_dir}")
        
        if not self.images_dir.exists():
            raise FileNotFoundError(f"Katalog z obrazami nie istnieje: {self.images_dir}")
    
    def detect_existing_structure(self) -> Dict[str, int]:
        """Wykryj istniejącą strukturę plików."""
        stats = {}
        
        # Sprawdź pliki list
        for split in ['train', 'val', 'test']:
            list_file = self.output_dir / f"{split}.txt"
            if list_file.exists():
                with open(list_file, 'r') as f:
                    count = sum(1 for line in f if line.strip())
                stats[f"{split}_list"] = count
                if self.verbose:
                    print(f"Znaleziono {split}.txt z {count} obrazami")
        
        # Sprawdź etykiety
        labels_dir = self.output_dir / "labels"
        if labels_dir.exists():
            for split in ['train', 'val', 'test']:
                split_dir = labels_dir / split
                if split_dir.exists():
                    txt_files = list(split_dir.glob("*.txt"))
                    stats[f"{split}_labels"] = len(txt_files)
                    if self.verbose:
                        print(f"Znaleziono {len(txt_files)} plików etykiet w labels/{split}/")
        
        return stats
    
    def get_class_names_from_coco(self) -> List[str]:
        """Pobierz nazwy klas z pliku COCO JSON."""
        if not self.coco_json_path or not self.coco_json_path.exists():
            return ["surgical_tool"]  # Domyślna klasa
        
        try:
            with open(self.coco_json_path, 'r', encoding='utf-8') as f:
                coco_data = json.load(f)
            
            categories = coco_data.get('categories', [])
            if not categories:
                return ["surgical_tool"]
            
            # Sortuj według ID
            categories.sort(key=lambda x: x['id'])
            
            # Zakładamy mapowanie wszystkich kategorii na klasę 0
            # (można to później zmienić)
            return [categories[0]['name']] if categories else ["surgical_tool"]
            
        except Exception as e:
            if self.verbose:
                print(f"Błąd wczytywania COCO JSON: {e}")
            return ["surgical_tool"]
    
    def create_dataset_yaml(self) -> None:
        """Stwórz plik dataset.yaml."""
        yaml_file = self.output_dir / "dataset.yaml"
        
        # Pobierz nazwy klas
        if not self.class_names:
            self.class_names = self.get_class_names_from_coco()
        
        # Sprawdź czy pliki list istnieją
        train_list = self.output_dir / "train.txt"
        val_list = self.output_dir / "val.txt"
        test_list = self.output_dir / "test.txt"
        
        yaml_content = f"""# {self.dataset_name} Dataset Configuration
# Generated by YOLOYamlCreator

# Dataset root directory
path: {self.output_dir}

# Image directories (wszystkie obrazy są w jednym folderze)
train: {self.images_dir}
val: {self.images_dir}
test: {self.images_dir}
"""
        
        # Dodaj listy jeśli istnieją
        if train_list.exists() and val_list.exists():
            yaml_content += f"""
# Image lists (zalecane dla YOLO)
train_list: {train_list}
val_list: {val_list}"""
            
            if test_list.exists():
                yaml_content += f"\ntest_list: {test_list}"
        
        yaml_content += f"""

# Classes
nc: {len(self.class_names)}  # Number of classes
names: {self.class_names}  # Class names

# Class indices
"""
        
        for i, name in enumerate(self.class_names):
            yaml_content += f"# {i}: {name}\n"
        
        # Zapisz plik
        try:
            with open(yaml_file, 'w', encoding='utf-8') as f:
                f.write(yaml_content)
            
            if self.verbose:
                print(f"\nUtworzono dataset.yaml: {yaml_file}")
        
        except Exception as e:
            print(f"BŁĄD: Nie można utworzyć dataset.yaml: {e}")
    
    def create_data_yaml(self) -> None:
        """Stwórz uproszczony plik data.yaml."""
        yaml_file = self.output_dir / "data.yaml"
        
        # Pobierz nazwy klas
        if not self.class_names:
            self.class_names = self.get_class_names_from_coco()
        
        # Sprawdź które pliki istnieją
        train_list = self.output_dir / "train.txt"
        val_list = self.output_dir / "val.txt"
        test_list = self.output_dir / "test.txt"
        
        yaml_content = f"""# YOLOv8 Dataset Configuration
# Simplified version for training

"""
        
        if train_list.exists():
            yaml_content += f"train: {train_list}\n"
        else:
            yaml_content += f"train: {self.images_dir}\n"
        
        if val_list.exists():
            yaml_content += f"val: {val_list}\n"
        else:
            yaml_content += f"val: {self.images_dir}\n"
        
        if test_list.exists():
            yaml_content += f"test: {test_list}\n"
        
        yaml_content += f"""
nc: {len(self.class_names)}
names: {self.class_names}
"""
        
        # Zapisz plik
        try:
            with open(yaml_file, 'w', encoding='utf-8') as f:
                f.write(yaml_content)
            
            if self.verbose:
                print(f"Utworzono data.yaml: {yaml_file}")
        
        except Exception as e:
            print(f"BŁĄD: Nie można utworzyć data.yaml: {e}")
    
    def create_training_config_yaml(self) -> None:
        """Stwórz przykładowy plik konfiguracyjny do treningu."""
        yaml_file = self.output_dir / "training_config.yaml"
        
        yaml_content = f"""# Training Configuration for YOLOv8
# Example configuration file

# Model
model: yolov8n.pt  # or yolov8s.pt, yolov8m.pt, yolov8l.pt, yolov8x.pt

# Dataset
data: {self.output_dir}/data.yaml

# Training parameters
epochs: 100
patience: 50
batch: 16
imgsz: 640

# Optimizer
optimizer: auto  # auto, SGD, Adam, AdamW
lr0: 0.01
lrf: 0.01
momentum: 0.937
weight_decay: 0.0005
warmup_epochs: 3.0
warmup_momentum: 0.8
warmup_bias_lr: 0.1

# Augmentation
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
degrees: 0.0
translate: 0.1
scale: 0.5
shear: 0.0
perspective: 0.0
flipud: 0.0
fliplr: 0.5
mosaic: 1.0
mixup: 0.0

# Other
workers: 8
project: {self.dataset_name}_results
name: exp
exist_ok: False
pretrained: True
verbose: True
seed: 0
deterministic: True
single_cls: False
image_weights: False
rect: False
cos_lr: False
close_mosaic: 0
resume: False
amp: True
overlap_mask: True
mask_ratio: 4
dropout: 0.0

# Inference
conf: 0.25
iou: 0.7
max_det: 300
"""
        
        try:
            with open(yaml_file, 'w', encoding='utf-8') as f:
                f.write(yaml_content)
            
            if self.verbose:
                print(f"Utworzono training_config.yaml: {yaml_file}")
        
        except Exception as e:
            print(f"BŁĄD: Nie można utworzyć training_config.yaml: {e}")
    
    def verify_dataset_structure(self) -> bool:
        """Zweryfikuj strukturę datasetu."""
        print("\n" + "=" * 60)
        print("WERYFIKACJA STRUKTURY DATASETU")
        print("=" * 60)
        
        all_good = True
        
        # Sprawdź główny katalog
        print(f"\n1. Katalog główny: {self.output_dir}")
        if self.output_dir.exists():
            print("   ✓ Istnieje")
        else:
            print("   ✗ Nie istnieje!")
            all_good = False
        
        # Sprawdź katalog obrazów
        print(f"\n2. Katalog obrazów: {self.images_dir}")
        if self.images_dir.exists():
            image_count = len(list(self.images_dir.glob("*.jpg")) + 
                            list(self.images_dir.glob("*.png")) +
                            list(self.images_dir.glob("*.jpeg")))
            print(f"   ✓ Istnieje ({image_count} obrazów)")
        else:
            print("   ✗ Nie istnieje!")
            all_good = False
        
        # Sprawdź pliki list
        print("\n3. Pliki list:")
        for split in ['train', 'val', 'test']:
            list_file = self.output_dir / f"{split}.txt"
            if list_file.exists():
                with open(list_file, 'r') as f:
                    count = sum(1 for line in f if line.strip())
                print(f"   ✓ {split}.txt: {count} obrazów")
            else:
                print(f"   ✗ {split}.txt: brak")
                if split != 'test':  # test jest opcjonalny
                    all_good = False
        
        # Sprawdź etykiety
        print("\n4. Pliki etykiet:")
        labels_dir = self.output_dir / "labels"
        if labels_dir.exists():
            for split in ['train', 'val', 'test']:
                split_dir = labels_dir / split
                if split_dir.exists():
                    txt_count = len(list(split_dir.glob("*.txt")))
                    print(f"   ✓ labels/{split}/: {txt_count} plików")
                else:
                    print(f"   ✗ labels/{split}/: brak")
                    if split != 'test':
                        all_good = False
        else:
            print("   ✗ Katalog labels/ nie istnieje!")
            all_good = False
        
        # Sprawdź pliki YAML
        print("\n5. Pliki konfiguracyjne:")
        for yaml_name in ['dataset.yaml', 'data.yaml']:
            yaml_file = self.output_dir / yaml_name
            if yaml_file.exists():
                print(f"   ✓ {yaml_name}: istnieje")
            else:
                print(f"   - {yaml_name}: brak (zostanie utworzony)")
        
        print("\n" + "=" * 60)
        
        return all_good


def main():
    parser = argparse.ArgumentParser(
        description='Tworzy pliki YAML dla istniejącego datasetu YOLO'
    )
    
    parser.add_argument(
        '--output_dir',
        type=str,
        required=True,
        help='Katalog z datasetm YOLO (gdzie są labels/, train.txt, itd.)'
    )
    
    parser.add_argument(
        '--images_dir',
        type=str,
        required=True,
        help='Katalog z obrazami'
    )
    
    parser.add_argument(
        '--coco_json',
        type=str,
        default=None,
        help='Opcjonalnie: plik COCO JSON do pobrania nazw klas'
    )
    
    parser.add_argument(
        '--class_names',
        type=str,
        nargs='+',
        default=None,
        help='Nazwy klas (np. --class_names surgical_tool scalpel forceps)'
    )
    
    parser.add_argument(
        '--dataset_name',
        type=str,
        default='surgical_tools',
        help='Nazwa datasetu'
    )
    
    parser.add_argument(
        '--create_training_config',
        action='store_true',
        help='Stwórz przykładowy plik konfiguracyjny treningu'
    )
    
    parser.add_argument(
        '--verify',
        action='store_true',
        default=True,
        help='Zweryfikuj strukturę datasetu'
    )
    
    args = parser.parse_args()
    
    try:
        creator = YOLOYamlCreator(
            output_dir=args.output_dir,
            images_dir=args.images_dir,
            coco_json_path=args.coco_json,
            class_names=args.class_names,
            dataset_name=args.dataset_name,
            verbose=True
        )
        
        # Wykryj istniejącą strukturę
        print("Wykrywanie istniejącej struktury...")
        stats = creator.detect_existing_structure()
        
        if not stats:
            print("\nUWAGA: Nie znaleziono żadnych plików datasetu!")
            print("Upewnij się, że wcześniej uruchomiłeś konwersję COCO→YOLO.")
        
        # Weryfikuj jeśli potrzeba
        if args.verify:
            creator.verify_dataset_structure()
        
        # Twórz pliki YAML
        print("\nTworzenie plików YAML...")
        creator.create_dataset_yaml()
        creator.create_data_yaml()
        
        if args.create_training_config:
            creator.create_training_config_yaml()
        
        print("\nGotowe! Możesz teraz trenować model używając:")
        print(f"  yolo train data={args.output_dir}/data.yaml model=yolov8n.pt epochs=100")
        
    except Exception as e:
        print(f"BŁĄD: {e}")
        import traceback
        traceback.print_exc()
        return 1
    
    return 0


if __name__ == "__main__":
    exit(main())