# Generate SSH Session Summary from Eden Cluster
# Pobiera dane z Eden SSH i zapisuje podsumowanie lokalnie
# Obsługuje różne JobId i dynamicznie znajduje logi
# Usage: .\generate-session-summary.ps1 [-JobId <id>] [-LogPath <path>] [-Description <text>]

param(
    [string]$JobId = "",
    [string]$LogPath = "",
    [string]$Description = ""
)

# Konfiguracja
$ProjectRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
$SessionDir = "$ProjectRoot\Eden\ClaudeSshSession"
$SessionTimestamp = Get-Date -Format "yyyy-MM-dd_HH-mm"
$SessionFolderName = "sesja_$SessionTimestamp"
$SessionPath = "$SessionDir\$SessionFolderName"

Write-Host "Session Summary Generator for Eden Cluster"
Write-Host "==========================================="
Write-Host "Timestamp: $SessionTimestamp (UTC)"
Write-Host "Session: $SessionFolderName"
if ($JobId -ne "") { Write-Host "Job ID: $JobId" }
if ($LogPath -ne "") { Write-Host "Log Path: $LogPath" }
Write-Host ""

# Utwórz katalog sesji
New-Item -ItemType Directory -Path $SessionPath -Force | Out-Null
Write-Host "[OK] Created session folder"

# Pobierz dane z Eden SSH
Write-Host "[FETCH] Retrieving data from Eden cluster..."

# Pobranie aktualnych jobów
$jobsStatus = ssh eden-cluster "squeue -u bpiotrowski -o '%.18i %.9P %.20j %.8u %.8T %.10M %.6D %R'" 2>&1
Write-Host "[OK] Retrieved current jobs"

# Pobranie statusu klastra
$clusterStatus = ssh eden-cluster "sfree" 2>&1
Write-Host "[OK] Retrieved cluster status"

# Pobranie statusu sprzętu
$hardwareStatus = ssh eden-cluster "nvidia-smi -L 2>/dev/null | head -10; sinfo -N -O nodehost,cpusstate,memory,statecompacted 2>/dev/null | head -10" 2>&1
Write-Host "[OK] Retrieved hardware status"

# Pobranie listy dostępnych logów
$logsList = ssh eden-cluster "find /mnt/evafs/faculty/home/bpiotrowski/DETR/logs -name '*.log' -type f 2>/dev/null | sort -r | head -20" 2>&1
Write-Host "[OK] Retrieved logs list"

# Pobranie informacji o konkretnym jobzie jeśli ID podane
$jobDetails = "No specific job ID provided"
$jobLog = "No job log retrieved"
$jobLogFile = ""

if ($JobId -ne "") {
    $jobDetails = ssh eden-cluster "scontrol show job $JobId" 2>&1
    Write-Host "[OK] Retrieved job details for ID: $JobId"

    # Znajdź log dla tego JobId
    if ($LogPath -eq "") {
        # Spróbuj znaleźć log automatycznie
        $logSearchResult = ssh eden-cluster "find /mnt/evafs/faculty/home/bpiotrowski/DETR/logs -name '*${JobId}*' -type f 2>/dev/null | head -1" 2>&1
        if ($logSearchResult -and $logSearchResult -ne "") {
            $LogPath = $logSearchResult
            Write-Host "[OK] Found log automatically: $LogPath"
        }
    }

    # Jeśli znaleźliśmy log, pobierz go
    if ($LogPath -ne "" -and $LogPath -notmatch "find: cannot") {
        $jobLog = ssh eden-cluster "tail -200 '$LogPath' 2>/dev/null || echo 'Log file not readable'" 2>&1
        Write-Host "[OK] Retrieved training log"
        $jobLogFile = $LogPath
    } else {
        # Fallback: spróbuj pobrać z domyślnych lokalizacji
        $defaultLogs = @(
            "/mnt/evafs/faculty/home/bpiotrowski/DETR/logs/detr_ddp_2gpu_500ep_${JobId}.log",
            "/mnt/evafs/faculty/home/bpiotrowski/DETR/logs/detr_ddp_3gpu_dgx3_${JobId}.log",
            "/mnt/evafs/faculty/home/bpiotrowski/DETR/logs/*.log"
        )

        foreach ($logFile in $defaultLogs) {
            $testLog = ssh eden-cluster "test -f '$logFile' && echo 'found' || echo 'not found'" 2>&1
            if ($testLog -match "found") {
                $jobLog = ssh eden-cluster "tail -200 '$logFile' 2>/dev/null" 2>&1
                $jobLogFile = $logFile
                Write-Host "[OK] Retrieved training log from: $logFile"
                break
            }
        }
    }
}

# Pobierz informacje o użyciu dysku
$diskUsage = ssh eden-cluster "du -sh /mnt/evafs/faculty/home/bpiotrowski/* 2>/dev/null | sort -rh | head -10" 2>&1
Write-Host "[OK] Retrieved disk usage"

# ===== TWORZENIE PLIKÓW =====
Write-Host ""
Write-Host "Generating files..."

# 1. SESSION_SUMMARY.md
$summaryContent = @"
# SSH Session Summary
**Session Date:** $SessionTimestamp UTC
**Session Folder:** $SessionFolderName
**Job ID:** $JobId
**Log Path:** $jobLogFile
**Description:** $Description

## Session Timestamp
\`\`\`
Generated: $SessionTimestamp
UTC Time
\`\`\`

## Current Jobs Status
\`\`\`
$jobsStatus
\`\`\`

## Job Details (ID: $JobId)
\`\`\`
$jobDetails
\`\`\`

## Job Training Log (Last 200 lines)
Log Source: $jobLogFile

\`\`\`
$jobLog
\`\`\`

## Cluster Status (sfree)
\`\`\`
$clusterStatus
\`\`\`

## Hardware Status
\`\`\`
$hardwareStatus
\`\`\`

## Disk Usage (Top 10)
\`\`\`
$diskUsage
\`\`\`

## Available Training Logs (Last 20)
\`\`\`
$logsList
\`\`\`

---
**Generated by:** generate-session-summary.ps1
**Session Rule:** F:\Studia\PhD_projekt\VIT\ViTParticleFilterTracker\Eden\ClaudeSshSession\SESSION_NAMING_RULE.md
"@

$summaryContent | Out-File "$SessionPath\SESSION_SUMMARY.md" -Encoding UTF8
Write-Host "[OK] Created SESSION_SUMMARY.md"

# 2. README.md
$readmeContent = @"
# Session: $SessionFolderName

**Created:** $SessionTimestamp UTC

## Quick Reference
- **Job ID:** $JobId
- **Log Path:** $jobLogFile
- **Description:** $Description
- **Folder:** $SessionFolderName

## Files in This Session
- **SESSION_SUMMARY.md** - Complete session data and status
- **README.md** - This file
- **cluster_status.txt** - Cluster resources snapshot
- **jobs_status.txt** - Current SLURM jobs
- **disk_usage.txt** - Disk usage summary

## How to Review
1. Open \`SESSION_SUMMARY.md\` for complete overview
2. Check \`jobs_status.txt\` for SLURM queue
3. Review \`cluster_status.txt\` for resource availability

## Session Management
- **Session Rule:** SESSION_NAMING_RULE.md in parent directory
- **All sessions:** F:\Studia\PhD_projekt\VIT\ViTParticleFilterTracker\Eden\ClaudeSshSession\
- **Next session:** Run \`.\generate-session-summary.ps1\` with different JobId

## Monitoring Commands

### Check specific job
\`\`\`bash
ssh eden-cluster "scontrol show job $JobId"
\`\`\`

### View full training log
\`\`\`bash
ssh eden-cluster "tail -f '$jobLogFile'"
\`\`\`

### Get cluster status
\`\`\`bash
ssh eden-cluster "sfree"
\`\`\`

### Find all logs for JobId
\`\`\`bash
ssh eden-cluster "find /mnt/evafs/faculty/home/bpiotrowski/DETR/logs -name '*$JobId*'"
\`\`\`

---
**Next Step:** Review SESSION_SUMMARY.md for details
"@

$readmeContent | Out-File "$SessionPath\README.md" -Encoding UTF8
Write-Host "[OK] Created README.md"

# 3. cluster_status.txt
$clusterStatus | Out-File "$SessionPath\cluster_status.txt" -Encoding UTF8
Write-Host "[OK] Created cluster_status.txt"

# 4. jobs_status.txt
$jobsStatus | Out-File "$SessionPath\jobs_status.txt" -Encoding UTF8
Write-Host "[OK] Created jobs_status.txt"

# 5. disk_usage.txt
$diskUsage | Out-File "$SessionPath\disk_usage.txt" -Encoding UTF8
Write-Host "[OK] Created disk_usage.txt"

# 6. job_details.txt (jeśli job ID podane)
if ($JobId -ne "") {
    $jobDetails | Out-File "$SessionPath\job_details.txt" -Encoding UTF8
    Write-Host "[OK] Created job_details.txt"
}

# 7. logs_available.txt
$logsList | Out-File "$SessionPath\logs_available.txt" -Encoding UTF8
Write-Host "[OK] Created logs_available.txt"

# ===== PODSUMOWANIE =====
Write-Host ""
Write-Host "Session Summary Generated Successfully"
Write-Host "======================================"
Write-Host ""
Write-Host "Session Folder: $SessionPath"
Write-Host "Folder Name: $SessionFolderName"
Write-Host ""
Write-Host "Files created:"
Get-ChildItem $SessionPath | ForEach-Object {
    $size = if ($_.Length) { "{0:N0} bytes" -f $_.Length } else { "dir" }
    Write-Host "  - $($_.Name) ($size)"
}
Write-Host ""
Write-Host "View summary:"
Write-Host "  $SessionPath\SESSION_SUMMARY.md"
Write-Host ""
Write-Host "Command to generate next session:"
Write-Host "  .\generate-session-summary.ps1 -JobId <NEW_JOB_ID> -Description <text>"
Write-Host ""
