background_ratio: 0.3
batch_size: 1
clustering_threshold: 0.7
detr_threshold: 0.8
dino_model: facebook/dino-vitb16
frames_per_video: 30
gentle_lr: 1e-6
gradient_accumulation_steps: 4
max_epochs: 3
max_retries: 1
min_cluster_size: 3
original_model_checkpoint: F:/Studia/PhD_projekt/VIT/ViTParticleFilterTracker/YOLO_DETR_Benchmarks/models/DETR/checkpoint_epoch_100.pth
output_directory: pipeline_output_single_test
python_executable: py
timeout_hours: 2
tooltip_ratio: 0.7
validation_split: 0.2
video_directory: E:/Cataract/videos/test_single
yolo_threshold: 0.3
